### ISSUE TITLE
How can I remove these blue borders around every window I have open?

### ISSUE THREAD

**Issue by lSANCHOl** [vinceliuice/Canvas-theme#2]
Is it possible to remove the blue borders that surround every window I open. I've looked throught the css but don't know css well enough to know what to change. 

p.s. if I can't remove it, how may I change the color of it?

blue borders: https://imgur.com/a/aoiAcxW

**Comment by antonfreeman** [comment]
Simplest way is to open src/gtk-3.0/gtk-light.css, src/gtk-3.0/gtk-dark.css, and src/gtk-3.0/gtk.css in a text editor and do a find+replace changing all occurrences of "0 0 0 1px rgba(93, 125, 251, 0.85)" to "0 0 0 0px rgba(93, 125, 251, 0.85)" then run ./Install again and reboot.

**Comment by vinceliuice** [comment]
I removed it
